const productList = [
    {
        id: 1,
        name: 'White dress shirt',
        category: 'Shirts',
        img: 'https://suitshop.com/static/80eb157de905172c1db0bf8d584f4798/cee19/CLASSIC_WHITE_SHIRT_009.jpg',
        price: 35,
        sizes: [
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: false },
        ],
        description: 'A smart spread-collar shirt is cut from finely textured yet substantial cotton and tailored with back pleats, a French placket and rounded, adjustable cuffs.',
        stock: 34,
        collection: ['essentials'],
    },
    {
        id: 2,
        name: 'Bogart Trench Coat',
        category: 'Coats',
        img: 'https://i8.amplience.net/i/indochino/15013992_0_0/brown-solid-design-trenchcoat.jpg?$suit-pdp-desk$',
        price: 120,
        sizes: [
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: false },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
        ],
        description: 'This classic men’s trench coat is made of two-ply Bacall® gabardine woven from combed, extra-long staple cotton. As a between-seasons coat, it can be worn all year round. The storm flaps of the coat‘s distinctively wide stand collar can be buttoned up and secured using the metal buckle. A back yoke and a shoulder yoke in the front left cover the shoulders.',
        stock: 5,
        collection: ['vintage', 'basic colours'],
        sale: true,
        oldPrice: '150'
    },
    {
        id: 3,
        category: 'Pants',
        name: 'Gray dress pant',
        img: 'https://cdn.shopify.com/s/files/1/0571/5122/6063/products/kd00436_med-grey_1-v2_2440x.jpg?v=1645555407',
        price: 75,
        sizes: [
            { name: '38', inStock: true },
            { name: '40', inStock: true },
            { name: '42', inStock: true },
            { name: '44', inStock: false },
            { name: '46', inStock: false },
            { name: '48', inStock: true },
        ],
        description: "Dress pants but make them affordable. Spice up your closet with a classic pair of wool dress pants in Light Grey that won't break the bank.",
        stock: 34,
        collection: ['essentials', 'basic colours'],
    },
    {
        id: 4,
        category: 'Pants',
        name: 'Blue dress pant',
        img: 'https://cdn.shopify.com/s/files/1/0098/0202/2971/products/original_50ed8c3c-078e-4a37-aebd-b30c832f7c70_600x.jpg?v=1575489695',
        price: 70,
        sizes: [
            { name: '38', inStock: true },
            { name: '40', inStock: true },
            { name: '42', inStock: true },
            { name: '44', inStock: false },
            { name: '46', inStock: true },
            { name: '48', inStock: true },
        ],
        description: "Dress pants but make them affordable. Spice up your closet with a classic pair of wool dress pants in Navy Blue that won't break the bank.",
        stock: 34
    },
    {
        id: 5,
        category: 'Pants',
        name: 'Black dress pant',
        img: 'https://www.baronboutique.com/wp-content/uploads/2020/09/mens-black-dress-pants.jpg',
        price: 70,
        sizes: [
            { name: '38', inStock: false },
            { name: '40', inStock: true },
            { name: '42', inStock: true },
            { name: '44', inStock: true },
            { name: '46', inStock: true },
            { name: '48', inStock: true },
        ],
        description: "Mens black dress pants offer distinctive looks that maintain a perfect balance between business and casual or work and wedding. Custom tailoring gives the black dress pants for men a spot-on fit. Crafted from cool and breathable merino wool-cashmere blend these black dress pants with belt loops and pockets are super comfortable and stylish. With wool’s natural stretch ankle-length black dress pants hold up against wrinkles very well.",
        stock: 34
    },
    {
        id: 6,
        category: 'Pants',
        name: 'Brown dress pant',
        img: 'https://n.nordstrommedia.com/id/sr3/c32e32a6-e3dd-476e-a72c-345416b02ee5.jpeg?h=365&w=240&dpr=2',
        price: 60,
        sizes: [
            { name: '38', inStock: true },
            { name: '40', inStock: true },
            { name: '42', inStock: true },
            { name: '44', inStock: true },
            { name: '46', inStock: true },
            { name: '48', inStock: true },
        ],
        description: "Mens brown dress pants offer distinctive looks that maintain a perfect balance between business and casual or work and wedding. Custom tailoring gives the black dress pants for men a spot-on fit. Crafted from cool and breathable merino wool-cashmere blend these black dress pants with belt loops and pockets are super comfortable and stylish. With wool’s natural stretch ankle-length black dress pants hold up against wrinkles very well.",
        stock: 34,
        collection: ['vintage', 'basic colours'],
        sale: true,
        oldPrice: 75

    },
    {
        id: 7,
        name: 'Blue dress shirt',
        category: 'Shirts',
        img: 'https://i5.walmartimages.com/asr/838d821e-a16f-4619-bccf-7d71fd8b157d_1.e501b98ceade80479394265ce1793713.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF',
        price: 36,
        sizes: [
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: false },
        ],
        description: 'A smart spread-collar shirt is cut from finely textured yet substantial cotton and tailored with back pleats, a French placket and rounded, adjustable cuffs.',
        stock: 34,
        collection: ['essentials'],
    },
    {
        id: 8,
        name: 'Bogart Suit',
        category: 'Suits',
        img: 'https://i.pinimg.com/564x/69/9d/57/699d57f76ee6e14a4f08243fae1f2a7a.jpg',
        price: 35,
        sizes: [
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: false },
        ],
        description: 'A smart spread-collar shirt is cut from finely textured yet substantial cotton and tailored with back pleats, a French placket and rounded, adjustable cuffs.',
        stock: 34,
        collection: ['vintage', 'basic colours'],
    },
    {
        id: 9,
        name: 'Marlon Suit',
        category: 'Suits',
        img: 'https://i.pinimg.com/564x/b7/9a/de/b79adef99eb0a579e026cf7633d41c3c.jpg',
        price: 35,
        sizes: [
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: false },
        ],
        description: 'A smart spread-collar shirt is cut from finely textured yet substantial cotton and tailored with back pleats, a French placket and rounded, adjustable cuffs.',
        stock: 34,
        collection: ['basic colours'],
    },
    {
        id: 10,
        name: 'Sheeran Jacket',
        category: 'Jackets',
        img: 'https://i.pinimg.com/736x/4b/7b/23/4b7b2327ae747223b25b641b3200055e.jpg',
        price: 35,
        sizes: [
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: false },
        ],
        description: 'A smart leather jacket is cut from finely textured yet substantial cotton and tailored with back pleats, a French placket and rounded, adjustable cuffs.',
        stock: 34,
        collection: ['vintage', 'essentials'],
    },
    {
        id: 11,
        name: 'Angelo Jacket',
        category: 'Jackets',
        img: 'https://i.pinimg.com/564x/a4/c4/f9/a4c4f9f35f9fe0249757db127019a699.jpg',
        price: 35,
        sizes: [
            { name: 'XS', inStock: false },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: false },
        ],
        description: 'A smart leather jacket is cut from finely textured yet substantial cotton and tailored with back pleats, a French placket and rounded, adjustable cuffs.',
        stock: 34,
    },
    {
        id: 12,
        name: '70s Wool Coat',
        category: 'Coats',
        img: 'https://cdn.webshopapp.com/shops/70373/files/98279246/vintage-coats-70s-men-wool-coats.jpg',
        price: 35,
        sizes: [
            { name: 'XS', inStock: false },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: false },
        ],
        description: 'A smart leather jacket is cut from finely textured yet substantial cotton and tailored with back pleats, a French placket and rounded, adjustable cuffs.',
        stock: 34,
        collection: ['vintage', 'basic colours'],
    },

];

export default productList;